import type { Theme } from './types'

const themes = [
  {
    name: 'darcula',
    colors: {
      background: '#212122',
      reservedWord: '#CC7832',
      typeName: '#4EC9B0',
      primitiveType: '#4EC9B0',
      number: '#6897BB',
      literal: '#CC7832',
      value: '#6897BB',
      string: '#6A8759',
      stringQuote: '#6A8759',
      comment: '#808080',
      className: '#FFC66D',
      functionDeclaration: '#FFC66D',
      functionCall: '#FFC66D',
      functionName: '#FFC66D',
      parameter: '#A9B7C6',
      variable: '#9876AA',
      member: '#A9B7C6',
      operator: '#A9B7C6',
      punctuation: '#D4D4D4',
      punctuationParen: '#D4D4D4',
      punctuationBrace: '#D4D4D4',
      punctuationDelimiter: '#D4D4D4',
      punctuationBracket: '#D4D4D4',
      punctuationDot: '#D4D4D4',
      punctuationEmptyCallParen: '#A9B7C6',
      plain: '#D4D4D4',
    },
    styles: {
      reservedWord: 'bold',
      typeName: 'bold',
      literal: 'bold',
      operator: 'bold',
    },
  },
  {
    name: 'deepdark-material-theme',
    colors: {
      background: '#080808',
      reservedWord: '#69F0AE',
      typeName: '#FFFB2A',
      primitiveType: '#FFFB2A',
      number: '#D0D0D0',
      literal: '#FF3E3E',
      value: '#D0D0D0',
      string: '#69F0AE',
      stringQuote: '#69F0AE',
      comment: '#808080',
      className: '#B8FCB1',
      functionDeclaration: '#80CBC4',
      functionCall: '#D68D5B',
      functionName: '#80CBC4',
      parameter: '#FF5E5E',
      variable: '#FFFFFF',
      operator: '#FF5E5E',
      punctuation: '#D0D0D0',
      punctuationParen: '#C9E9E0',
      punctuationBrace: '#D0D0D0',
      punctuationDelimiter: '#D0D0D0',
      punctuationBracket: '#FFFFFF',
      plain: '#FFFFFF',
    },
    styles: {},
  },
  {
    name: 'dracula',
    semanticTheme: 'DRACULA',
    colors: {
      background: '#282A36',
      reservedWord: '#FF79C6',
      typeName: '#8BE9FD',
      primitiveType: '#8BE9FD',
      value: '#BD93F9',
      string: '#F1FA8C',
      stringQuote: '#E9F284',
      comment: '#6272A4',
      className: '#8BE9FD',
      functionName: '#50FA7B',
      parameter: '#FFB86C',
      variable: '#F8F8F2',
      operator: '#FF79C6',
      punctuation: '#F8F8F2',
      punctuationParen: '#F8F8F2',
      punctuationBrace: '#F8F8F2',
      punctuationDelimiter: '#F8F8F2',
      punctuationBracket: '#F8F8F2',
      punctuationDot: '#F8F8F2',
      plain: '#F8F8F2',
    },
    styles: {
      typeName: 'italic',
      parameter: 'italic',
    },
  },
  {
    name: 'gruvbox-dark-hard',
    semanticTheme: 'GRUVBOX_DARK',
    colors: {
      background: '#1D2021',
      reservedWord: '#FE8019',
      typeName: '#FABD2F',
      primitiveType: '#FE8019',
      value: '#D3869B',
      string: '#B8BB26',
      stringQuote: '#A89984',
      comment: '#928374',
      className: '#FABD2F',
      functionName: '#FABD2F',
      parameterType: '#FE8019',
      parameter: '#83A598',
      variable: '#EBDBB2',
      operator: '#8EC07C',
      punctuation: '#A89984',
      punctuationParen: '#A89984',
      punctuationBrace: '#A89984',
      punctuationDelimiter: '#A89984',
      punctuationBracket: '#A89984',
      punctuationDot: '#A89984',
      plain: '#EBDBB2',
    },
    styles: {
      comment: 'italic',
    },
  },
  {
    name: 'jarvis-3d',
    colors: {
      background: '#0A1628',
      reservedWord: '#4D9FFF',
      typeName: '#4D9FFF',
      primitiveType: '#4D9FFF',
      parameterType: '#4D9FFF',
      number: '#FFD95A',
      literal: '#FF9D5A',
      value: '#FFD95A',
      string: '#00FF9F',
      stringQuote: '#00FF9F',
      comment: '#4D7A9F',
      className: '#7AB8FF',
      functionName: '#00D9FF',
      parameter: '#8DC9E6',
      variable: '#B8D9EB',
      member: '#B8D9EB',
      operator: '#00D9FF',
      punctuation: '#E0F7FF',
      punctuationParen: '#E0F7FF',
      punctuationBrace: '#E0F7FF',
      punctuationDelimiter: '#E0F7FF',
      punctuationBracket: '#E0F7FF',
      punctuationDot: '#E0F7FF',
      plain: '#E0F7FF',
    },
    styles: {
      reservedWord: 'bold',
      typeName: 'bold',
      className: 'bold',
      functionName: 'bold',
      operator: 'bold',
      parameter: 'italic',
      comment: 'italic',
    },
  },
  {
    name: 'monokai-night',
    colors: {
      background: '#1F1F1F',
      reservedWord: '#F92672',
      typeName: '#66D9EF',
      primitiveType: '#66D9EF',
      value: '#AE81FF',
      string: '#E6DB74',
      stringQuote: '#E6DB74',
      comment: '#75715E',
      className: '#A6E22E',
      functionName: '#A6E22E',
      parameter: '#FD971F',
      variable: '#F8F8F2',
      operator: '#F92672',
      punctuation: '#DDDDDD',
      punctuationParen: '#DDDDDD',
      punctuationBrace: '#DDDDDD',
      punctuationDelimiter: '#DDDDDD',
      punctuationBracket: '#DDDDDD',
      punctuationDot: '#DDDDDD',
      plain: '#F8F8F2',
    },
    styles: {
      typeName: 'italic',
      parameter: 'italic',
      className: 'underline',
    },
  },
  {
    name: 'monokai-pro-filter-spectrum',
    colors: {
      background: '#222222',
      reservedWord: '#FC618D',
      typeName: '#5AD4E6',
      primitiveType: '#5AD4E6',
      value: '#948AE3',
      string: '#FCE566',
      stringQuote: '#8B888F',
      comment: '#69676C',
      className: '#5AD4E6',
      functionName: '#7BD88F',
      parameter: '#FD9353',
      variable: '#F7F1FF',
      operator: '#FC618D',
      punctuation: '#8B888F',
      punctuationParen: '#8B888F',
      punctuationBrace: '#8B888F',
      punctuationDelimiter: '#8B888F',
      punctuationBracket: '#8B888F',
      punctuationDot: '#8B888F',
      plain: '#F7F1FF',
    },
    styles: {
      reservedWord: 'italic',
      typeName: 'italic',
      parameter: 'italic',
      comment: 'italic',
    },
  },
  {
    name: 'nord',
    semanticTheme: 'NORD',
    colors: {
      background: '#2E3440',
      reservedWord: '#81A1C1',
      typeName: '#8FBCBB',
      primitiveType: '#81A1C1',
      literal: '#81A1C1',
      value: '#B48EAD',
      string: '#A3BE8C',
      stringQuote: '#ECEFF4',
      comment: '#616E88',
      className: '#8FBCBB',
      functionName: '#88C0D0',
      parameter: '#D8DEE9',
      variable: '#D8DEE9',
      operator: '#81A1C1',
      punctuation: '#ECEFF4',
      punctuationParen: '#ECEFF4',
      punctuationBrace: '#ECEFF4',
      punctuationDelimiter: '#81A1C1',
      punctuationBracket: '#ECEFF4',
      punctuationDot: '#ECEFF4',
      plain: '#D8DEE9',
    },
    styles: {},
  },
  {
    name: 'one-dark-pro-night-flat',
    colors: {
      background: '#16191D',
      reservedWord: '#C678DD',
      typeName: '#E5C07B',
      primitiveType: '#C678DD',
      value: '#D19A66',
      string: '#98C379',
      stringQuote: '#98C379',
      comment: '#7F848E',
      className: '#E5C07B',
      functionName: '#61AFEF',
      parameter: '#E06C75',
      variable: '#E06C75',
      member: '#E5C07B',
      operator: '#56B6C2',
      punctuation: '#ABB2BF',
      punctuationParen: '#ABB2BF',
      punctuationBrace: '#ABB2BF',
      punctuationDelimiter: '#ABB2BF',
      punctuationBracket: '#ABB2BF',
      punctuationDot: '#ABB2BF',
      plain: '#ABB2BF',
    },
    styles: {},
  },
  {
    name: 'synthwave-84',
    semanticTheme: 'SYNTHWAVE_84',
    colors: {
      background: '#262335',
      reservedWord: '#FEDE5D',
      typeName: '#FEDE5D',
      primitiveType: '#FEDE5D',
      value: '#F97E72',
      string: '#FF8B39',
      stringQuote: '#FF8B39',
      comment: '#848BBD',
      className: '#FE4450',
      functionName: '#36F9F6',
      parameter: '#FF7EDB',
      variable: '#FF7EDB',
      operator: '#FFFFFFEE',
      punctuation: '#BBBBBB',
      punctuationParen: '#BBBBBB',
      punctuationBrace: '#BBBBBB',
      punctuationDelimiter: '#BBBBBB',
      punctuationBracket: '#BBBBBB',
      punctuationDot: '#BBBBBB',
      plain: '#BBBBBB',
    },
    styles: {
      comment: 'italic',
      parameter: 'italic',
    },
  },
  {
    name: 'tokyo-night',
    semanticTheme: 'TOKYO_NIGHT',
    colors: {
      background: '#1A1B26',
      reservedWord: '#9D7CD8',
      typeName: '#BB9AF7',
      primitiveType: '#BB9AF7',
      value: '#FF9E64',
      string: '#9ECE6A',
      stringQuote: '#89DDFF',
      comment: '#51597D',
      className: '#C0CAF5',
      functionName: '#7AA2F7',
      parameter: '#E0AF68',
      variable: '#C0CAF5',
      operator: '#89DDFF',
      punctuation: '#9ABDF5',
      punctuationParen: '#9ABDF5',
      punctuationBrace: '#9ABDF5',
      punctuationDelimiter: '#89DDFF',
      punctuationBracket: '#89DDFF',
      punctuationDot: '#89DDFF',
      plain: '#A9B1D6',
    },
    styles: {
      reservedWord: 'italic',
      comment: 'italic',
    },
  },
] satisfies Theme[]

themes.sort((left, right) => left.name.localeCompare(right.name))

export { themes }
